### ISSUE TITLE
Received response status [FAILED] from custom resource. Message returned: SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by fasatrix** [cloudcomponents/cdk-constructs#119]
`Issues shows with package Version: 1.41.0`
`Latest working package for us 1.38.1`

Stack Error:
```
   89/101 |2:46:48 pm | CREATE_FAILED        | Custom::BlueGreenService                  | CdPipeline-catalogue-statics/Ecs-CdPipeline-catalogue-statics/CR-Ecs-CdPipeline-catalogue-statics/Default (CdPipelinecataloguestaticsEcsCdPip
elinecataloguestaticsCREcsCdPipelinecataloguestatics0F03ECBD) Received response status [FAILED] from custom resource. Message returned: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at getProperties (/var/task/index.js:120:35)
    at onCreate (/var/task/index.js:123:245)
    at handler (/var/task/index.js:210:20)
    at Runtime.handler (/var/task/__entrypoint__.js:31:30)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25) (RequestId: 462ac0c7-d0de-4efa-b5d7-c3dfa52e2437)
        new CustomResource (D:\LINZ\step-cdk\node_modules\@aws-cdk\core\lib\custom-resource.ts:36:21)
        \_ new EcsService (D:\LINZ\step-cdk\node_modules\@cloudcomponents\cdk-blue-green-container-deployment\src\ecs-service.ts:107:21)
```

We tried to instantiate ECS with  different configs some are the following, is there anything we miss? From error it would appear that whatever is passed down to the JSON.parse seems to be  an object already?:

```
   const ecsService = new EcsService(this, `Ecs-${id}`, {
        cluster,
        serviceName,
        desiredCount,
        taskDefinition,
        prodTargetGroup: props.prodTargetGroup,
      }); 
```

```
   const ecsService = new EcsService(this, `Ecs-${id}`, {
        cluster,
        serviceName,
        desiredCount,
        taskDefinition,
        prodTargetGroup: props.prodTargetGroup,
        maxHealthyPercent: 200,
        minHealthyPercent: 50,
        circuitBreaker: { rollback: true },
        healthCheckGracePeriod: Duration.seconds(5),
      });
```

**Comment by fasatrix** [comment]
@hupe1980  any chance to look at this problem? From our investigation It was introduced with the ECS additional configuration changes, but we couldn't figure it out why
